src/Entity/Application.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ApplicationRepository")
 */
class Application
{
    const STATUS_WAITING = 0;
    const STATUS_ACCEPTED = 1;
    const STATUS_REJECTED = 2;

    const STATUS = [
        self::STATUS_WAITING => "En attente",
        self::STATUS_ACCEPTED => "Acceptée",
        self::STATUS_REJECTED => "Rejetée",
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="text")
     */
    private $text;

    /**
     * @ORM\Column(type="integer")
     *
     * @var integer
     */
    private $status;

    /**
     * @var Job
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Job", inversedBy="applications")
     * @ORM\JoinColumn(nullable=false)
     */
    private $job;

    /**
     * @var UserInfo
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\UserInfo", inversedBy="applications")
     * @ORM\JoinColumn(nullable=false)
     */
    private $userInfo;

    public function __construct()
    {
        $this->created_at = new \DateTime('now');
        $this->status = self::STATUS_WAITING;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getStatus(): int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;
        return $this;
    }

    public function getStatusString(): string
    {
        return self::STATUS[$this->status];
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getJob(): Job
    {
        return $this->job;
    }

    public function setJob(Job $job): self
    {
        $this->job = $job;

        return $this;
    }

    public function getUserInfo(): UserInfo
    {
        return $this->userInfo;
    }

    public function setUserInfo(UserInfo $userInfo): self
    {
        $this->userInfo = $userInfo;

        return $this;
    }
}

src/Entity/Job.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\JobRepository")
 */
class Job
{
    const TYPE = [
        "Emploi plein temps",
        "Emploi mi temps",
        "Stage",
        "Travail saisonnier",
    ];

    const SHORT_TYPE = [
        "Plein temps",
        "Mi temps",
        "Stage",
        "Saisonnier",
    ];

    public static function getTypeChoices() {
        $choices = [];
        foreach (self::TYPE as $index => $val) {
            $choices[$val] = $index;
        }
        return $choices;
    }
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $type;

    /**
     * @ORM\Column(type="datetime")
     */
    private $limit_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @var Profile
     *
     * @ORM\OneToOne(targetEntity="App\Entity\Profile", inversedBy="job", cascade={"persist", "remove"})
     */
    private $bestProfile;

    /**
     * @var Collection
     *
     * @ORM\OneToMany(targetEntity="App\Entity\Application", mappedBy="job", cascade={"remove"})
     */
    private $applications;

    public function __construct()
    {
        $this->created_at = new \DateTime('now');
        $this->limit_date = new \DateTime('now');
        $this->applications = new ArrayCollection();
    }

    /**
     * @var Society
     *
     * @ORM\ManyToOne(targetEntity="Society", inversedBy="jobs")
     */
    private $society;

    public function getId()
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function setType(int $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getLimitDate(): ?\DateTimeInterface
    {
        return $this->limit_date;
    }

    public function setLimitDate(\DateTimeInterface $limit_date): self
    {
        $this->limit_date = $limit_date;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getCreateAt(): \DateTime
    {
        return $this->created_at;
    }

    /**
     * @return Society|null
     */
    public function getSociety(): ?Society
    {
        return $this->society;
    }

    /**
     * @param Society $society
     * @return Job
     */
    public function setSociety(Society $society): self
    {
        $this->society = $society;

        return $this;
    }

    /**
     * @return Profile|null
     */
    public function getBestProfile(): ?Profile
    {
        return $this->bestProfile;
    }

    /**
     * @param Profile $profile
     * @return Job
     */
    public function setBestProfile(Profile $profile): self
    {
        $this->bestProfile = $profile;

        return $this;
    }

    public function getApplications(): Collection
    {
        return $this->applications;
    }

    public function addApplication(Application $application): self
    {
        $this->applications->add($application);

        return $this;
    }

    public function removeApplication(Application $application): self
    {
        $this->applications->removeElement($application);

        return $this;
    }
}

src/Controller/CandidateJobController.php
<?php

namespace App\Controller;

use App\Entity\Application;
use App\Entity\Job;
use App\Entity\Society;
use App\Form\ApplicationType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class CandidateJobController extends Controller
{
    /**
     * @Route("/candidate/jobs/{page}", name="candidate_browse_jobs", requirements={"page": "\d+"}, defaults={"page": 1})
     *
     * @param int $page
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function browseJobs(int $page) {
        $user = $this->getUser();
        if (!$user->isValid()) {
            $this->addFlash('warning', 'Veuillez compléter votre profil avant de consulter les offres.');
            return $this->redirectToRoute('candidate_edit_profile');
        }

        $jobRepo = $this->getDoctrine()->getManager()->getRepository('App:Job');

        $jobsPager = $jobRepo->search();

        $jobsPager->setMaxPerPage(5);
        $jobsPager->setCurrentPage($page);


        return $this->render('candidate_job/browseJobs.html.twig', [
            'jobsPager' => $jobsPager,
            'shortTypes' => Job::SHORT_TYPE,
        ]);
    }

    /**
     * @Route("/candidate/job/{id}", name="candidate_show_job", requirements={"id": "\d+"})
     *
     * @param int $id
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function showJob(Request $request, int $id) {
        $em = $this->getDoctrine()->getManager();
        $jobRepo = $em->getRepository('App:Job');

        $job = $jobRepo->get($id);

        if ($job === null) throw $this->createNotFoundException();

        $application = new Application();
        $application->setUserInfo($this->getUser()->getUserInfo());
        $application->setJob($job);

        $applicationForm = $this->createForm(ApplicationType::class, $application);
        $applicationForm->handleRequest($request);

        if ($applicationForm->isSubmitted() && $applicationForm->isValid()) {
            $em->persist($application);
            $em->flush();

            $this->addFlash('success', 'Candidature envoyée.');
            return $this->redirectToRoute('candidate_show_job', [
                'id' => $job->getId(),
            ]);
        }

        return $this->render('candidate_job/showJob.html.twig', [
            'job' => $job,
            'society' => $job->getSociety(),
            'applicationForm' => $applicationForm->createView(),
            'sectors' => Society::SECTORS,
        ]);
    }

    /**
     * @Route("/candidate/applications/{page}", name="candidate_show_applications", requirements={"page": "\d+"}, defaults={"page": 1})
     *
     * @param int $page
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function showApplications(int $page)
    {
        $applicationRepo = $this->getDoctrine()->getManager()->getRepository('App:Application');

        $appPager = $applicationRepo->getAllByUser($this->getUser());

        $appPager->setMaxPerPage(5);
        $appPager->setCurrentPage($page);

        return $this->render('candidate_job/showApplications.html.twig', [
            'appPager' => $appPager,
        ]);
    }
}

templates/candidate_job/browseJobs.html.twig
{% extends 'candidateBase.html.twig' %}

{% block body %}
    <div id="content">
        <div class="container">
            <div class="row">
                {{ include("candidate_job/sidebar.html.twig") }}
                <div class="col-md-8 col-sm-8 col-xs-12">
                    {% for job in jobsPager.currentPageResults %}
                        <div class="job-list">
                            <div class="thumb">
                                <a href="job-details.html"><img src="assets/img/jobs/img-1.jpg" alt=""></a>
                            </div>
                            <div class="job-list-content">
                                <h4><a href="{{ path('candidate_show_job', {'id': job.id}) }}">{{ job.title }}<span class="full-time">{{ shortTypes[job.type] }}</span></a></h4>
                                <p>{{ job.description|nl2br }}</p>
                                <div class="job-tag">
                                    <div class="pull-right">
                                        <a
                                            href="{{ path('candidate_show_job', {'id': job.id}) }}"
                                           class="btn btn-common btn-rm"
                                        >
                                            Plus d'infos
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                    <br>
                    <div class="pagerfanta pager">
                        {{ pagerfanta(jobsPager, 'twitter_bootstrap3_translated') }}
                    </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/candidate_job/showApplications.html.twig
{% extends 'candidateBase.html.twig' %}

{% block body %}
    <div id="content">
        <div class="container">
            <div class="row">
                {{ include('candidate_job/sidebar.html.twig') }}
                <div class="col-md-8 col-sm-8 col-xs-12">
                    <div class="job-alerts-item candidates">
                        <h3 class="alerts-title">Mes candidatures</h3>
                        <div class="alerts-list">
                            <div class="row">
                                <div class="col-md-3">
                                    <p>Offre</p>
                                </div>
                                <div class="col-md-3">
                                    <p>Envoyé le</p>
                                </div>
                                <div class="col-md-3">
                                    <p>Status</p>
                                </div>

                            </div>
                        </div>
                        {% for application in appPager.currentPageResults %}
                            <div class="alerts-content">
                                <div class="row">
                                    <div class="col-md-3">
                                        <h3><a href="{{ path('candidate_show_job', { 'id': application.job.id }) }}">{{ application.job.title }}</a></h3>
                                    </div>
                                    <div class="col-md-3">
                                        <p>{{ application.createdAt | date('d/m/Y') }}</p>
                                    </div>
                                    <div class="col-md-3">
                                        <p>{{ application.statusString }}</p>
                                    </div>
                                    <div class="col-md-3">
                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                        <br>
                        <div class="pagerfanta pager">
                            {{ pagerfanta(appPager, 'twitter_bootstrap3_translated') }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/candidate_job/showJob.html.twig
{% extends 'candidateBase.html.twig' %}

{% block body %}
    <section class="job-detail section">
        <div class="container">
            <div class="row">
                {% for label, messages in app.flashes %}
                    {% for message in messages %}
                        <div class="flash-message alert alert-{{ label }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endfor %}
            </div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="header-detail">
                        <div class="header-content pull-left">
                            <h3><a>{{ job.title }}</a></h3>
                            <p><span>Annonce mise à jour le {{ job.createAt | date }}</span></p>
                            <hr/>
                            <h4>L'entreprise</h4>
                            <p>{{ society.description|nl2br }}</p>
                            <h4>Description de l'offre</h4>
                            <p>{{ job.description|nl2br }}</p>
                        </div>
                        <div class="detail-company pull-right text-right">
                            <div class="img-thum">
                                <img class="img-responsive" src="assets/img/jobs/recent-job-detail.jpg" alt="">
                            </div>
                            <div class="name">
                                <h3>Entreprise :</h3>
                                <h4>{{ society.name }}</h4>
                                <h5>{{ sectors[society.sector] }}</h5>
                            </div>
                        </div>
                        <div class="clearfix">
                            <div class="meta">
                                <button
                                    type="button"
                                    class="btn btn-border btn-sm"
                                    data-toggle="modal"
                                    data-target="#applicationModal"
                                >
                                    <i class="ti-email"></i> Postuler
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Application Modal -->
    <div id="applicationModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                {{ form_start(applicationForm) }}
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Envoyer une candidature</h4>
                </div>
                <div class="modal-body">
                    Ce message sera joint aux informations de votre profil (cv, description, etc...).
                    {{ form_row(applicationForm._token) }}

                    {{ form_row(applicationForm.text, { 'label': 'Message', 'attr': { 'rows': 10 }}) }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-border btn-danger btn-sm" data-dismiss="modal">Annuler</button>
                    <input type="submit" class="btn btn-border btn-sm" value="Envoyer" />
                </div>
                {{ form_end(applicationForm) }}
            </div>

        </div>
    </div>
{% endblock %}

templates/candidate_job/sidebar.html.twig
<div class="col-md-4 col-sm-4 col-xs-12">
    <div class="right-sideabr">
        <div class="inner-box">
            <h4>Menu</h4>
            <ul class="lest item">
                <li>
                    <a
                        href="{{ path('candidate_browse_jobs') }}"
                        class="{{ current_path in ['candidate_browse_jobs'] ? 'active' : '' }}"
                    >
                        Parcourir les offres
                    </a>
                </li>
                <li>
                    <a
                            href="{{ path('candidate_show_applications') }}"
                            class="{{ current_path in ['candidate_show_applications'] ? 'active' : '' }}"
                    >
                        Mes candidatures
                    </a>
            </ul>
        </div>
    </div>
</div>