src/Entity/Application.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ApplicationRepository")
 */
class Application
{
    const STATUS_WAITING = 0;
    const STATUS_ACCEPTED = 1;
    const STATUS_REJECTED = 2;

    const STATUS = [
        self::STATUS_WAITING => "En attente",
        self::STATUS_ACCEPTED => "Acceptée",
        self::STATUS_REJECTED => "Rejetée",
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="text")
     */
    private $text;

    /**
     * @ORM\Column(type="integer")
     *
     * @var integer
     */
    private $status;

    /**
     * @var Job
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Job", inversedBy="applications")
     * @ORM\JoinColumn(nullable=false)
     */
    private $job;

    /**
     * @var UserInfo
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\UserInfo", inversedBy="applications")
     * @ORM\JoinColumn(nullable=false)
     */
    private $userInfo;

    public function __construct()
    {
        $this->created_at = new \DateTime('now');
        $this->status = self::STATUS_WAITING;
    }

    public function getId()
    {
        return $this->id;
    }

    public function getStatus(): int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;
        return $this;
    }

    public function getStatusString(): string
    {
        return self::STATUS[$this->status];
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getJob(): Job
    {
        return $this->job;
    }

    public function setJob(Job $job): self
    {
        $this->job = $job;

        return $this;
    }

    public function getUserInfo(): UserInfo
    {
        return $this->userInfo;
    }

    public function setUserInfo(UserInfo $userInfo): self
    {
        $this->userInfo = $userInfo;

        return $this;
    }
}

src/Entity/Job.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\JobRepository")
 */
class Job
{
    const TYPE = [
        "Emploi plein temps",
        "Emploi mi temps",
        "Stage",
        "Travail saisonnier",
    ];

    const SHORT_TYPE = [
        "Plein temps",
        "Mi temps",
        "Stage",
        "Saisonnier",
    ];

    public static function getTypeChoices() {
        $choices = [];
        foreach (self::TYPE as $index => $val) {
            $choices[$val] = $index;
        }
        return $choices;
    }
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $type;

    /**
     * @ORM\Column(type="datetime")
     */
    private $limit_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @var Profile
     *
     * @ORM\OneToOne(targetEntity="App\Entity\Profile", inversedBy="job", cascade={"persist", "remove"})
     */
    private $bestProfile;

    /**
     * @var Collection
     *
     * @ORM\OneToMany(targetEntity="App\Entity\Application", mappedBy="job", cascade={"remove"})
     */
    private $applications;

    public function __construct()
    {
        $this->created_at = new \DateTime('now');
        $this->limit_date = new \DateTime('now');
        $this->applications = new ArrayCollection();
    }

    /**
     * @var Society
     *
     * @ORM\ManyToOne(targetEntity="Society", inversedBy="jobs")
     */
    private $society;

    public function getId()
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function setType(int $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getLimitDate(): ?\DateTimeInterface
    {
        return $this->limit_date;
    }

    public function setLimitDate(\DateTimeInterface $limit_date): self
    {
        $this->limit_date = $limit_date;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getCreateAt(): \DateTime
    {
        return $this->created_at;
    }

    /**
     * @return Society|null
     */
    public function getSociety(): ?Society
    {
        return $this->society;
    }

    /**
     * @param Society $society
     * @return Job
     */
    public function setSociety(Society $society): self
    {
        $this->society = $society;

        return $this;
    }

    /**
     * @return Profile|null
     */
    public function getBestProfile(): ?Profile
    {
        return $this->bestProfile;
    }

    /**
     * @param Profile $profile
     * @return Job
     */
    public function setBestProfile(Profile $profile): self
    {
        $this->bestProfile = $profile;

        return $this;
    }

    public function getApplications(): Collection
    {
        return $this->applications;
    }

    public function addApplication(Application $application): self
    {
        $this->applications->add($application);

        return $this;
    }

    public function removeApplication(Application $application): self
    {
        $this->applications->removeElement($application);

        return $this;
    }
}

src/Controller/SocietyJobController.php
<?php

namespace App\Controller;

use App\Entity\Application;
use App\Entity\Job;
use App\Entity\Profile;
use App\Entity\UserInfo;
use App\Form\JobType;
use App\Form\ProfileStep1Type;
use App\Form\ProfileStep2Type;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class SocietyJobController extends Controller
{
    /**
     * @Route("/society/new_job", name="society_post_job")
     *
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function postJob(Request $request)
    {
        $user = $this->getUser();

        $job = new Job();
        $job->setSociety($user->getSociety());

        return $this->jobForm($request, $job, true);
    }


    /**
     * @Route("/society/job/{id}", name="society_edit_job", requirements={"id": "\d+"})
     *
     * @param Request $request
     * @param int $id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function editJob(Request $request, int $id)
    {
        $jobRepo = $this->getDoctrine()->getManager()->getRepository('App:Job');
        $job = $jobRepo->find($id);
        if ($job === null) {
            throw $this->createNotFoundException("Offre non trouvée.");
        }

        return $this->jobForm($request, $job, false);
    }

    private function jobForm(Request $request, Job $job, bool $new)
    {
        $em = $this->getDoctrine()->getManager();
        $form = $this->createForm(JobType::class, $job);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em->persist($job);
            $em->flush();

            if ($new)
                $this->addFlash('success', 'Offre crée.');
            else
                $this->addFlash('success', 'Offre mise à jour.');

            return $this->redirectToRoute('society_edit_best_profile', [
                'id' => $job->getId(),
            ]);
        }

        return $this->render('society_job/postJob.html.twig', [
            'form' => $form->createView(),
            'new' => $new,
        ]);
    }

    /**
     * @Route("/society/jobs/{page}", name="society_show_jobs", requirements={"page": "\d+"}, defaults={"page": 1})
     * @param int $page
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function index(int $page)
    {
        $user = $this->getUser();
        if (!$user->isValid()) {
            $this->addFlash('warning', 'Veuillez compléter le profil de votre entreprise avant de continuer.');
            return $this->redirectToRoute('society_edit_profile');
        }

        $jobRepo = $this->getDoctrine()->getManager()->getRepository('App:Job');

        $mySociety = $this->getUser()->getSociety();
        $jobsPager = $jobRepo->getSocietyJobs($mySociety);

        $jobsPager->setMaxPerPage(5);
        $jobsPager->setCurrentPage($page);

        return $this->render('society_job/index.html.twig', [
            'jobsPager' => $jobsPager,
            'shortTypes' => Job::SHORT_TYPE,
        ]);
    }

    /**
     * @Route("/society/applications/{page}", name="society_show_applications", requirements={"page": "\d+"}, defaults={"page": 1})
     *
     * @param int $page
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function showApplications(int $page)
    {
        $applicationRepo = $this->getDoctrine()->getManager()->getRepository('App:Application');

        $mySociety = $this->getUser()->getSociety();
        $appPager = $applicationRepo->getAllBySociety($mySociety);

        $appPager->setMaxPerPage(5);
        $appPager->setCurrentPage($page);

        return $this->render('society_job/showApplications.html.twig', [
            'appPager' => $appPager,
        ]);
    }

    /**
     * @Route("/society/application/{id}", name="society_show_application", requirements={"id": "\d+"})
     */
    public function showApplication(int $id)
    {
        $applicationRepo = $this->getDoctrine()->getManager()->getRepository('App:Application');

        $mySociety = $this->getUser()->getSociety();
        $application = $applicationRepo->get($id);

        if ($application === null || $application->getJob()->getSociety()->getId() !== $mySociety->getId()) {
            throw $this->createNotFoundException();
        }

        return $this->render('society_job/showApplication.html.twig', [
            'application' => $application,
            'userStatus' => UserInfo::STATUS,
        ]);
    }

    /**
     * @Route("/society/application/{id}/{action}",
     *     name="society_set_application_status",
     *     requirements={
     *         "id": "\d+",
     *         "action": "(accept|reject)"
     *     })
     *
     * @param int $id
     * @param string $action
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpKernel\Exception\NotFoundHttpException
     */
    public function setApplicationStatus(int $id, string $action)
    {
        $em = $this->getDoctrine()->getManager();
        $applicationRepo = $em->getRepository('App:Application');

        $mySociety = $this->getUser()->getSociety();
        $application = $applicationRepo->get($id);

        if ($application === null || $application->getJob()->getSociety()->getId() !== $mySociety->getId()) {
            return $this->createNotFoundException();
        }

        if ($action === 'accept') {
            $application->setStatus(Application::STATUS_ACCEPTED);
        } else {
            $application->setStatus(Application::STATUS_REJECTED);
        }

        $em->persist($application);
        $em->flush();

        $this->addFlash('success', 'Status de la canditure modifié.');

        return $this->redirectToRoute('society_show_application', [
            'id' => $id,
        ]);
    }

    /**
     * @Route("/society/job/{id}/best_profile", name="society_edit_best_profile", requirements={"id": "\d+"})
     *
     * @param Request $request
     * @param int $id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function editDetailedProfileStep1(Request $request, int $id)
    {
        $user = $this->getUser();
        $dm = $this->getDoctrine()->getManager();

        // Check the job id
        $job = $dm->getRepository('App:Job')->get($id);
        if (!$job) {
            throw $this->createNotFoundException();
        }

        // Get all categories
        $categoriesRaw = $dm->getRepository('App:Category')->getAll();
        $categories = [];

        // Set categories to use category's id as an array index
        foreach ($categoriesRaw as $category) {
            $categories[$category->getId()] = $category;
        }

        $profile = $dm->getRepository('App:Profile')->getByJob($job) ?: new Profile();
        $profile->setJob($job);
        $oldCategories = clone $profile->getProfileCategories();

        $selectedCat = [];
        foreach ($profile->getProfileCategories() as $category) {
            $selectedCat[] = $category->getCategory()->getId();
        }

        $form = $this->createForm(ProfileStep1Type::class, $profile);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if (count($profile->getProfileCategories()) <= 0) {
                $this->addFlash('danger', 'Veuillez choisir au moins une catégorie.');
            } else if (count($profile->getProfileCategories()) > 5) {
                $this->addFlash('danger', 'Vous ne pouvez pas choisir plus de 5 catégories.');
            } else {
                foreach ($profile->getProfileCategories() as $category) {
                    $category->setProfile($profile);
                }

                // Remove old categories
                foreach ($oldCategories as $c) {
                    if (!$this->searchInCollection($c->getId(), $profile->getProfileCategories())) {
                        $dm->remove($c);
                    }
                }

                $job->setBestProfile($profile);

                $dm->persist($job);
                $dm->flush();

                return $this->redirectToRoute('society_edit_best_profile_step2', [
                    'step' => 2,
                    'id' => $id,
                ]);
            }
        }

        return $this->render('society_job/editBestProfile.html.twig', [
            'form' => $form->createView(),
            'userProfile' => $profile,
            'categories' => $categories,
            'selectedCategories' => $selectedCat,
        ]);
    }

    /**
     * id should start at 2
     *
     * @Route("/society/job/{id}/best_profile/{step}", name="society_edit_best_profile_step2", requirements={"step": "\d+", "id": "\d+"})
     *
     * @param Request $request
     * @param int $step
     * @param int $id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function editDetailedProfileStep2(Request $request, int $step, int $id)
    {
        if ($step === 0 || $step === 1)
            return $this->editDetailedProfileStep1($request, $id);

        $dm = $this->getDoctrine()->getManager();

        // Check the job id
        $job = $dm->getRepository('App:Job')->get($id);

        if (!$job) {
            throw $this->createNotFoundException();
        }

        $user = $this->getUser();

        // Get all profileCategories of the user to check the step number and get the right category
        $categories = $dm->getRepository('App:ProfileCategory')->getAllByJob($job);
        if (count($categories) + 1 < $step) {
            throw $this->createNotFoundException();
        }
        $category = $categories[$step - 2]->getCategory();

templates/society_job/browseProfiles.html.twig
{% extends 'societyBase.html.twig' %}

{% block body %}
    <div id="content">
        <div class="container">
            <div class="row">
                {% for label, messages in app.flashes %}
                    {% for message in messages %}
                        <div class="flash-message alert alert-{{ label }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endfor %}
            </div>
            <div class="row">
                {{ include('society_job/sidebar.html.twig') }}
                <div class="col-md-8 col-sm-8 col-xs-12">
                    <div class="job-alerts-item candidates">
                        <h3 class="alerts-title">Profils correspondants</h3>
                        <div class="alerts-list">
                            <div class="row">
                                <div class="col-md-4">
                                    <p>Nom</p>
                                </div>
                                <div class="col-md-4">
                                    <p>score</p>
                                </div>
                                <div class="col-md-4">
                                </div>
                            </div>
                        </div>
                        {% for candidate in candidates %}
                            <div class="alerts-content">
                                <div class="row">
                                    <div class="col-md-4">
                                        <p>
                                            <b>
                                                <a href="#">
                                                    {{ candidate.firstName }} {{ candidate.lastName }}
                                                </a>
                                            </b>
                                        </p>
                                    </div>
                                    <div class="col-md-4">
                                        <p style="color: rgb({{ ((100-scores[candidate.id])*256/100) | round }}, {{ (scores[candidate.id]*256/100) | round }}, 0)">{{ scores[candidate.id] }}</p>
                                    </div>
                                    <div class="col-md-4">
                                       <a href="{{ path('society_show_profile', {'id': candidate.profile.id}) }}" class="btn btn-common">Voir le profil</a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                        <br>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/society_job/index.html.twig
{% extends 'societyBase.html.twig' %}

{% block body %}
    <div id="content">
        <div class="container">
            <div class="row">
                {% for label, messages in app.flashes %}
                    {% for message in messages %}
                        <div class="flash-message alert alert-{{ label }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endfor %}
            </div>
            <div class="row">
                {{ include('society_job/sidebar.html.twig') }}
                <div class="col-md-8 col-sm-8 col-xs-12">
                    <div class="job-alerts-item candidates">
                        <h3 class="alerts-title">Mes offres</h3>
                        <div class="alerts-list">
                            <div class="row">
                                <div class="col-md-3">
                                    <p>Titre</p>
                                </div>
                                <div class="col-md-3">
                                    <p>Type</p>
                                </div>
                                <div class="col-md-3">
                                    <p>Candidatures</p>
                                </div>
                                <div class="col-md-3">
                                    <p>Date limite</p>
                                </div>
                            </div>
                        </div>
                        {% for job in jobsPager.currentPageResults %}
                            <div class="alerts-content">
                                <div class="row">
                                    <div class="col-md-3">
                                        <h3><a href="{{ path('society_edit_job', { 'id': job.id }) }}">{{ job.title }}</a></h3>
                                    </div>
                                    <div class="col-md-3">
                                        <p><span class="full-time">{{ shortTypes[job.type] }}</span></p>
                                    </div>
                                    <div class="col-md-3">
                                        <p>{{ job.applications | length }}</p>
                                    </div>
                                    <div class="col-md-3">
                                        <p>{{ job.limitDate | date('d/m/Y')}}</p>
                                    </div>
                                </div>
                                <div>
                                    {% if job.bestProfile != null %}
                                        <a
                                            href="{{ path('society_browse_candidates', {'id': job.id}) }}"
                                            class="btn btn-common btn-sm"
                                        >
                                            Consulter les profils interessants
                                        </a>
                                    {% else %}
                                        <p>Il faut définir un profil idéal pour accéder aux profils</p>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}

                        <br>
                        <div class="pagerfanta pager">
                            {{ pagerfanta(jobsPager, 'twitter_bootstrap3_translated') }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/society_job/postJob.html.twig
{% extends 'societyBase.html.twig' %}

{% block body %}
    <div id="content">
        <div class="container">
            <div class="row">
                {% for label, messages in app.flashes %}
                    {% for message in messages %}
                        <div class="alert alert-{{ label }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endfor %}
            </div>
            <div class="row">
                {{ include('society_job/sidebar.html.twig') }}
                <div class="col-md-8 col-sm-8 col-xs-12">
                    <div class="page-ads box">
                        {{ form_start(form) }}
                        {{ form_row(form._token) }}

                        <div class="divider"><h3>{{ new ? 'Créer une nouvelle offre' : 'Modifier une offre' }}</h3></div>
                        {{ form_row(form.title, { 'label': 'Titre' }) }}
                        {{ form_row(form.description, { 'label': 'Description', 'attr': { 'rows': 10 }}) }}
                        {{ form_row(form.type, { 'label': 'Type' }) }}
                        {{ form_row(form.limit_date, { 'label': 'Date limite' }) }}

                        <input type="submit" class="btn btn-common" value="Suivant" />

                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/society_job/showApplication.html.twig
{% extends 'societyBase.html.twig' %}

{% block body %}
    <div id="content">
        <div class="container">
            <div class="row">
                {% for label, messages in app.flashes %}
                    {% for message in messages %}
                        <div class="flash-message alert alert-{{ label }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endfor %}
            </div>
            <div class="row">
                {{ include('society_job/sidebar.html.twig') }}
                <div class="col-md-8 col-sm-8 col-xs-12">
                    <div class="job-alerts-item candidates">
                        <h3 class="alerts-title">
                            Candidature à <a
                                    href="{{ path('society_edit_job', { 'id': application.job.id }) }}">{{ application.job.title }}</a>
                        </h3>
                        <p class="center">Status : {{ application.statusString }}</p>
                        <div class="row">
                            <h4>Message du candidat</h4>
                            <div>
                                {{ application.text|nl2br }}
                            </div>
                            <hr/>
                            <h4>CV(s)</h4>
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>Langue</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for cv in application.userInfo.cvs %}
                                    <tr>
                                        <td>{{ cv.lang }}</td>
                                        <td><a href="{{ vich_uploader_asset(cv, 'cvFile') }}">Télécharger</a></td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                            <hr/>
                            <h4>Profil du candidat</h4>
                            <div class="row">
                                <div class="col-sm-4">
                                    <p><b>Prénom :</b><br/>{{ application.userInfo.firstName }}</p>
                                </div>
                                <div class="col-sm-4">
                                    <p><b>Nom : </b><br/>{{ application.userInfo.lastName }}</p>
                                </div>
                                <div class="col-sm-4">
                                    <p><b>Status : </b><br/>{{ userStatus[application.userInfo.status] }}</p>
                                </div>
                            </div>
                            <p><b>Adresse mail :</b><br/>{{ application.userInfo.user.email }}</p>
                            <p><b>Description :</b><br/>{{ application.userInfo.description|nl2br }}</p>
                            <hr/>
                            <div class="row">
                                <div class="col-sm-6 center">
                                    <a
                                        href="{{ path('society_set_application_status', {'id': application.id, 'action': 'reject'}) }}"
                                        class="btn btn-sm btn-border"
                                    >
                                        Refuser
                                    </a>
                                </div>
                                <div class="col-sm-6 center">
                                    <a
                                            href="{{ path('society_set_application_status', {'id': application.id, 'action': 'accept'}) }}"
                                            class="btn btn-sm btn-border"
                                    >
                                        Accepter
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Application Modal -->
    <div id="applicationModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                TODO
            </div>

        </div>
    </div>
{% endblock %}

templates/society_job/showApplications.html.twig
{% extends 'societyBase.html.twig' %}

{% block body %}
    <div id="content">
        <div class="container">
            <div class="row">
                {{ include('society_job/sidebar.html.twig') }}
                <div class="col-md-8 col-sm-8 col-xs-12">
                    <div class="job-alerts-item candidates">
                        <h3 class="alerts-title">Candidatures reçues</h3>
                        <div class="alerts-list">
                            <div class="row">
                                <div class="col-md-3">
                                    <p>Offre</p>
                                </div>
                                <div class="col-md-3">
                                    <p>Reçu le</p>
                                </div>
                                <div class="col-md-3">
                                    <p>Status</p>
                                </div>

                            </div>
                        </div>
                        {% for application in appPager.currentPageResults %}
                            <div class="alerts-content">
                                <div class="row">
                                    <div class="col-md-3">
                                        <h3><a href="{{ path('society_edit_job', { 'id': application.job.id }) }}">{{ application.job.title }}</a></h3>
                                    </div>
                                    <div class="col-md-3">
                                        <p>{{ application.createdAt | date('d/m/Y') }}</p>
                                    </div>
                                    <div class="col-md-3">
                                        <p>{{ application.statusString }}</p>
                                    </div>
                                    <div class="col-md-3">
                                        <p><a href="{{ path('society_show_application', { 'id': application.id }) }}">Voir la candidature</a></p>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                        <br>
                        <div class="pagerfanta pager">
                            {{ pagerfanta(appPager, 'twitter_bootstrap3_translated') }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}